name: 新澳门六合彩预测

on:
  workflow_dispatch:
  schedule:
    # 北京时间每30分钟运行
    - cron: '*/30 * * * *'

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:

      - name: 拉取仓库
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 创建数据库目录
        run: |
          mkdir -p data

      - name: 缓存数据库
        uses: actions/cache@v4
        with:
          path: |
            new_macau.db
          key: new-macau-db

      - name: 运行新澳门预测
        run: |
          python new_macau.py sync

      - name: 上传数据库
        uses: actions/upload-artifact@v4
        with:
          name: new-macau-db
          path: new_macau.db